<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-0FSTDRC" name="com.freshproposals.selenium.Lost_Proposal_Verification" tests="6" failures="1" timestamp="2020-01-17T15:59:03 IST" time="61.979" errors="0">
  <testcase name="login" time="0.684" classname="com.freshproposals.selenium.Lost_Proposal_Verification"/>
  <testcase name="Dashboard_Get_Lost_Value" time="5.800" classname="com.freshproposals.selenium.Lost_Proposal_Verification"/>
  <testcase name="createproposal" time="34.473" classname="com.freshproposals.selenium.Lost_Proposal_Verification"/>
  <testcase name="Send_and_Copy" time="17.183" classname="com.freshproposals.selenium.Lost_Proposal_Verification"/>
  <testcase name="Dashboard_Verify_Lost_Value" time="3.839" classname="com.freshproposals.selenium.Lost_Proposal_Verification">
    <failure type="java.lang.AssertionError" message="did not expect to find [15] but found [15]">
      <![CDATA[java.lang.AssertionError: did not expect to find [15] but found [15]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1401)
at org.testng.Assert.assertNotEquals(Assert.java:1406)
at com.freshproposals.selenium.Lost_Proposal_Verification.Dashboard_Verify_Lost_Value(Lost_Proposal_Verification.java:133)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$45/1908143486.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Dashboard_Verify_Lost_Value -->
  <testcase name="contentLibrary" classname="com.freshproposals.selenium.Lost_Proposal_Verification">
    <skipped/>
  </testcase> <!-- contentLibrary -->
</testsuite> <!-- com.freshproposals.selenium.Lost_Proposal_Verification -->
